name: Android Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Proje Dosyalarını Çek
      - name: Checkout repository
        uses: actions/checkout@v3

      # Output Artifact Yükle
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./Output/

      # Python Ayarları
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Bağımlılıkları Yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-appiumlibrary
          pip install Appium-Python-Client

      # Android SDK ve Emulator Ayarları
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          emulator-options: "-no-window -no-audio"

      # APK Yükle
      - name: Install APK
        run: adb install ./Beewa.apk

      # Appium Server Başlat
      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --log-level error &
        timeout-minutes: 3

      # Robot Framework Testlerini Çalıştır
      - name: Run Robot Framework Tests
        run: |
          sleep 30
          robot -d Output tests/

      # Test Sonuçlarını Yükle
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: robot-framework-results
          path: ./Output/
