name: Android Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manuel başlatmayı aktif eder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the project
      - name: Check out code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies (Robot Framework, Appium-Python-Client, etc.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-appiumlibrary
          pip install Appium-Python-Client

      # Set up Android SDK and Emulator
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: android-30
          arch: x86_64
          profile: Pixel_4
          emulator-options: "-no-window -no-audio"

      # Start Android Emulator
      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Pixel_4
          emulator-options: "-no-window -no-audio"

      # Install the APK on the Android Emulator
      - name: Install APK
        run: adb install ./app-debug.apk  # APK dosyasının doğru yolu

      # Start Appium Server
      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --log-level error &
        timeout-minutes: 3

      # Run Robot Framework Tests
      - name: Run Robot Framework Tests
        run: |
          sleep 30
          robot -d output tests/

      # Publish Test Results
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: robot-framework-results
          path: output/
